import type { Player } from "./types"

export const SEEDED_PLAYERS: Player[] = [
  {
    id: "messi",
    name: "Lionel Messi",
    image: "",
    nationality: "Argentina",
    nationalityFlag: "https://flagcdn.com/ar.svg",
    position: "Forward",
    teams: [
      { teamId: "barcelona", teamName: "Barcelona", startYear: 2004, endYear: 2021, logo: "https://crests.football-data.org/81.png" },
      { teamId: "psg", teamName: "Paris Saint-Germain", startYear: 2021, endYear: 2023, logo: "https://crests.football-data.org/524.png" },
      { teamId: "inter-miami", teamName: "Inter Miami", startYear: 2023, endYear: undefined },
    ],
  },
  {
    id: "ronaldo",
    name: "Cristiano Ronaldo",
    image: "",
    nationality: "Portugal",
    nationalityFlag: "https://flagcdn.com/pt.svg",
    position: "Forward",
    teams: [
      { teamId: "sporting", teamName: "Sporting CP", startYear: 2002, endYear: 2003 },
      { teamId: "man-united", teamName: "Manchester United", startYear: 2003, endYear: 2009 },
      { teamId: "real-madrid", teamName: "Real Madrid", startYear: 2009, endYear: 2018 },
      { teamId: "juventus", teamName: "Juventus", startYear: 2018, endYear: 2021 },
      { teamId: "man-united", teamName: "Manchester United", startYear: 2021, endYear: 2022 },
      { teamId: "al-nassr", teamName: "Al Nassr", startYear: 2023, endYear: undefined },
    ],
  },
  {
    id: "neymar",
    name: "Neymar Jr",
    image: "",
    nationality: "Brazil",
    nationalityFlag: "https://flagcdn.com/br.svg",
    position: "Forward",
    teams: [
      { teamId: "santos", teamName: "Santos", startYear: 2009, endYear: 2013 },
      { teamId: "barcelona", teamName: "Barcelona", startYear: 2013, endYear: 2017 },
      { teamId: "psg", teamName: "Paris Saint-Germain", startYear: 2017, endYear: 2023 },
      { teamId: "al-hilal", teamName: "Al Hilal", startYear: 2023, endYear: undefined },
    ],
  },
  {
    id: "mbappe",
    name: "Kylian Mbappé",
    image: "",
    nationality: "France",
    nationalityFlag: "https://flagcdn.com/fr.svg",
    position: "Forward",
    teams: [
      { teamId: "monaco", teamName: "AS Monaco", startYear: 2015, endYear: 2017 },
      { teamId: "psg", teamName: "Paris Saint-Germain", startYear: 2017, endYear: 2024 },
      { teamId: "real-madrid", teamName: "Real Madrid", startYear: 2024, endYear: undefined },
    ],
  },
  {
    id: "haaland",
    name: "Erling Haaland",
    image: "",
    nationality: "Norway",
    nationalityFlag: "https://flagcdn.com/no.svg",
    position: "Forward",
    teams: [
      { teamId: "molde", teamName: "Molde FK", startYear: 2017, endYear: 2018 },
      { teamId: "salzburg", teamName: "Red Bull Salzburg", startYear: 2019, endYear: 2019 },
      { teamId: "dortmund", teamName: "Borussia Dortmund", startYear: 2020, endYear: 2022 },
      { teamId: "man-city", teamName: "Manchester City", startYear: 2022, endYear: undefined },
    ],
  },
  {
    id: "de-bruyne",
    name: "Kevin De Bruyne",
    image: "",
    nationality: "Belgium",
    nationalityFlag: "https://flagcdn.com/be.svg",
    position: "Midfielder",
    teams: [
      { teamId: "genk", teamName: "KRC Genk", startYear: 2008, endYear: 2012 },
      { teamId: "chelsea", teamName: "Chelsea", startYear: 2012, endYear: 2014 },
      { teamId: "wolfsburg", teamName: "VfL Wolfsburg", startYear: 2014, endYear: 2015 },
      { teamId: "man-city", teamName: "Manchester City", startYear: 2015, endYear: undefined },
    ],
  },
  {
    id: "salah",
    name: "Mohamed Salah",
    image: "",
    nationality: "Egypt",
    nationalityFlag: "https://flagcdn.com/eg.svg",
    position: "Forward",
    teams: [
      { teamId: "basel", teamName: "FC Basel", startYear: 2010, endYear: 2012 },
      { teamId: "chelsea", teamName: "Chelsea", startYear: 2012, endYear: 2014 },
      { teamId: "fiorentina", teamName: "Fiorentina", startYear: 2015, endYear: 2015 },
      { teamId: "roma", teamName: "AS Roma", startYear: 2015, endYear: 2017 },
      { teamId: "liverpool", teamName: "Liverpool", startYear: 2017, endYear: undefined },
    ],
  },
  {
    id: "lewandowski",
    name: "Robert Lewandowski",
    image: "",
    nationality: "Poland",
    nationalityFlag: "https://flagcdn.com/pl.svg",
    position: "Forward",
    teams: [
      { teamId: "lech", teamName: "Lech Poznań", startYear: 2008, endYear: 2010 },
      { teamId: "dortmund", teamName: "Borussia Dortmund", startYear: 2010, endYear: 2014 },
      { teamId: "bayern", teamName: "Bayern Munich", startYear: 2014, endYear: 2022 },
      { teamId: "barcelona", teamName: "Barcelona", startYear: 2022, endYear: undefined },
    ],
  },
  {
    id: "kane",
    name: "Harry Kane",
    image: "",
    nationality: "England",
    nationalityFlag: "https://flagcdn.com/gb-eng.svg",
    position: "Forward",
    teams: [
      { teamId: "tottenham", teamName: "Tottenham Hotspur", startYear: 2009, endYear: 2023 },
      { teamId: "bayern", teamName: "Bayern Munich", startYear: 2023, endYear: undefined },
    ],
  },
  {
    id: "bellingham",
    name: "Jude Bellingham",
    image: "",
    nationality: "England",
    nationalityFlag: "https://flagcdn.com/gb-eng.svg",
    position: "Midfielder",
    teams: [
      { teamId: "birmingham", teamName: "Birmingham City", startYear: 2019, endYear: 2020 },
      { teamId: "dortmund", teamName: "Borussia Dortmund", startYear: 2020, endYear: 2023 },
      { teamId: "real-madrid", teamName: "Real Madrid", startYear: 2023, endYear: undefined },
    ],
  },
  {
    id: "vinicius",
    name: "Vinícius Jr",
    image: "",
    nationality: "Brazil",
    nationalityFlag: "https://flagcdn.com/br.svg",
    position: "Forward",
    teams: [
      { teamId: "flamengo", teamName: "Flamengo", startYear: 2017, endYear: 2018 },
      { teamId: "real-madrid", teamName: "Real Madrid", startYear: 2018, endYear: undefined },
    ],
  },
  {
    id: "modric",
    name: "Luka Modrić",
    image: "",
    nationality: "Croatia",
    nationalityFlag: "https://flagcdn.com/hr.svg",
    position: "Midfielder",
    teams: [
      { teamId: "dinamo", teamName: "Dinamo Zagreb", startYear: 2003, endYear: 2008 },
      { teamId: "tottenham", teamName: "Tottenham Hotspur", startYear: 2008, endYear: 2012 },
      { teamId: "real-madrid", teamName: "Real Madrid", startYear: 2012, endYear: undefined },
    ],
  },
  {
    id: "kroos",
    name: "Toni Kroos",
    image: "",
    nationality: "Germany",
    nationalityFlag: "https://flagcdn.com/de.svg",
    position: "Midfielder",
    teams: [
      { teamId: "bayern", teamName: "Bayern Munich", startYear: 2007, endYear: 2014 },
      { teamId: "real-madrid", teamName: "Real Madrid", startYear: 2014, endYear: 2024 },
    ],
  },
  {
    id: "busquets",
    name: "Sergio Busquets",
    image: "",
    nationality: "Spain",
    nationalityFlag: "https://flagcdn.com/es.svg",
    position: "Midfielder",
    teams: [
      { teamId: "barcelona", teamName: "Barcelona", startYear: 2008, endYear: 2023 },
      { teamId: "inter-miami", teamName: "Inter Miami", startYear: 2023, endYear: undefined },
    ],
  },
  {
    id: "iniesta",
    name: "Andrés Iniesta",
    image: "",
    nationality: "Spain",
    nationalityFlag: "https://flagcdn.com/es.svg",
    position: "Midfielder",
    teams: [
      { teamId: "barcelona", teamName: "Barcelona", startYear: 2002, endYear: 2018 },
      { teamId: "vissel-kobe", teamName: "Vissel Kobe", startYear: 2018, endYear: 2023 },
    ],
  },
  {
    id: "alisson",
    name: "Alisson Becker",
    image: "",
    nationality: "Brazil",
    nationalityFlag: "https://flagcdn.com/br.svg",
    position: "Goalkeeper",
    teams: [
      { teamId: "internacional", teamName: "Internacional", startYear: 2013, endYear: 2016 },
      { teamId: "roma", teamName: "AS Roma", startYear: 2016, endYear: 2018 },
      { teamId: "liverpool", teamName: "Liverpool", startYear: 2018, endYear: undefined },
    ],
  },
  {
    id: "van-dijk",
    name: "Virgil van Dijk",
    image: "",
    nationality: "Netherlands",
    nationalityFlag: "https://flagcdn.com/nl.svg",
    position: "Defender",
    teams: [
      { teamId: "groningen", teamName: "FC Groningen", startYear: 2011, endYear: 2013 },
      { teamId: "celtic", teamName: "Celtic", startYear: 2013, endYear: 2015 },
      { teamId: "southampton", teamName: "Southampton", startYear: 2015, endYear: 2018 },
      { teamId: "liverpool", teamName: "Liverpool", startYear: 2018, endYear: undefined },
    ],
  },
  {
    id: "salah",
    name: "Mohamed Salah",
    image: "",
    nationality: "Egypt",
    nationalityFlag: "https://flagcdn.com/eg.svg",
    position: "Forward",
    teams: [
      { teamId: "basel", teamName: "FC Basel", startYear: 2010, endYear: 2012 },
      { teamId: "chelsea", teamName: "Chelsea", startYear: 2012, endYear: 2014 },
      { teamId: "fiorentina", teamName: "Fiorentina", startYear: 2015, endYear: 2015 },
      { teamId: "roma", teamName: "AS Roma", startYear: 2015, endYear: 2017 },
      { teamId: "liverpool", teamName: "Liverpool", startYear: 2017, endYear: undefined },
    ],
  },
  {
    id: "rodri",
    name: "Rodri",
    image: "",
    nationality: "Spain",
    nationalityFlag: "https://flagcdn.com/es.svg",
    position: "Midfielder",
    teams: [
      { teamId: "villarreal", teamName: "Villarreal", startYear: 2015, endYear: 2018 },
      { teamId: "atletico", teamName: "Atlético Madrid", startYear: 2018, endYear: 2019 },
      { teamId: "man-city", teamName: "Manchester City", startYear: 2019, endYear: undefined },
    ],
  },
  {
    id: "foden",
    name: "Phil Foden",
    image: "",
    nationality: "England",
    nationalityFlag: "https://flagcdn.com/gb-eng.svg",
    position: "Midfielder",
    teams: [
      { teamId: "man-city", teamName: "Manchester City", startYear: 2017, endYear: undefined },
    ],
  },
  {
    id: "saka",
    name: "Bukayo Saka",
    image: "",
    nationality: "England",
    nationalityFlag: "https://flagcdn.com/gb-eng.svg",
    position: "Forward",
    teams: [
      { teamId: "arsenal", teamName: "Arsenal", startYear: 2018, endYear: undefined },
    ],
  },
  {
    id: "odegaard",
    name: "Martin Ødegaard",
    image: "",
    nationality: "Norway",
    nationalityFlag: "https://flagcdn.com/no.svg",
    position: "Midfielder",
    teams: [
      { teamId: "stromsgodset", teamName: "Strømsgodset", startYear: 2014, endYear: 2015 },
      { teamId: "real-madrid", teamName: "Real Madrid", startYear: 2015, endYear: 2017 },
      { teamId: "heerenveen", teamName: "SC Heerenveen", startYear: 2017, endYear: 2018 },
      { teamId: "vitesse", teamName: "Vitesse", startYear: 2018, endYear: 2019 },
      { teamId: "real-sociedad", teamName: "Real Sociedad", startYear: 2019, endYear: 2021 },
      { teamId: "arsenal", teamName: "Arsenal", startYear: 2021, endYear: undefined },
    ],
  },
  {
    id: "saliba",
    name: "William Saliba",
    image: "",
    nationality: "France",
    nationalityFlag: "https://flagcdn.com/fr.svg",
    position: "Defender",
    teams: [
      { teamId: "saint-etienne", teamName: "AS Saint-Étienne", startYear: 2018, endYear: 2021 },
      { teamId: "nice", teamName: "OGC Nice", startYear: 2021, endYear: 2021 },
      { teamId: "marseille", teamName: "Olympique Marseille", startYear: 2021, endYear: 2022 },
      { teamId: "arsenal", teamName: "Arsenal", startYear: 2022, endYear: undefined },
    ],
  },
  {
    id: "musiala",
    name: "Jamal Musiala",
    image: "",
    nationality: "Germany",
    nationalityFlag: "https://flagcdn.com/de.svg",
    position: "Midfielder",
    teams: [
      { teamId: "bayern", teamName: "Bayern Munich", startYear: 2019, endYear: undefined },
    ],
  },
  {
    id: "wirtz",
    name: "Florian Wirtz",
    image: "",
    nationality: "Germany",
    nationalityFlag: "https://flagcdn.com/de.svg",
    position: "Midfielder",
    teams: [
      { teamId: "leverkusen", teamName: "Bayer Leverkusen", startYear: 2020, endYear: undefined },
    ],
  },
  {
    id: "trent",
    name: "Trent Alexander-Arnold",
    image: "",
    nationality: "England",
    nationalityFlag: "https://flagcdn.com/gb-eng.svg",
    position: "Defender",
    teams: [
      { teamId: "liverpool", teamName: "Liverpool", startYear: 2016, endYear: undefined },
    ],
  },
  {
    id: "rice",
    name: "Declan Rice",
    image: "",
    nationality: "England",
    nationalityFlag: "https://flagcdn.com/gb-eng.svg",
    position: "Midfielder",
    teams: [
      { teamId: "west-ham", teamName: "West Ham United", startYear: 2017, endYear: 2023 },
      { teamId: "arsenal", teamName: "Arsenal", startYear: 2023, endYear: undefined },
    ],
  },
  {
    id: "havertz",
    name: "Kai Havertz",
    image: "",
    nationality: "Germany",
    nationalityFlag: "https://flagcdn.com/de.svg",
    position: "Midfielder",
    teams: [
      { teamId: "leverkusen", teamName: "Bayer Leverkusen", startYear: 2016, endYear: 2020 },
      { teamId: "chelsea", teamName: "Chelsea", startYear: 2020, endYear: 2023 },
      { teamId: "arsenal", teamName: "Arsenal", startYear: 2023, endYear: undefined },
    ],
  },
  {
    id: "courtois",
    name: "Thibaut Courtois",
    image: "",
    nationality: "Belgium",
    nationalityFlag: "https://flagcdn.com/be.svg",
    position: "Goalkeeper",
    teams: [
      { teamId: "genk", teamName: "KRC Genk", startYear: 2009, endYear: 2011 },
      { teamId: "chelsea", teamName: "Chelsea", startYear: 2011, endYear: 2018 },
      { teamId: "atletico", teamName: "Atlético Madrid", startYear: 2011, endYear: 2014 },
      { teamId: "real-madrid", teamName: "Real Madrid", startYear: 2018, endYear: undefined },
    ],
  },
  {
    id: "valverde",
    name: "Federico Valverde",
    image: "",
    nationality: "Uruguay",
    nationalityFlag: "https://flagcdn.com/uy.svg",
    position: "Midfielder",
    teams: [
      { teamId: "penarol", teamName: "Peñarol", startYear: 2015, endYear: 2016 },
      { teamId: "real-madrid", teamName: "Real Madrid", startYear: 2016, endYear: undefined },
    ],
  },
  {
    id: "pique",
    name: "Gerard Piqué",
    image: "",
    nationality: "Spain",
    nationalityFlag: "https://flagcdn.com/es.svg",
    position: "Defender",
    teams: [
      { teamId: "man-united", teamName: "Manchester United", startYear: 2004, endYear: 2008 },
      { teamId: "barcelona", teamName: "Barcelona", startYear: 2008, endYear: 2022 },
    ],
  },
  {
    id: "r9",
    name: "Ronaldo Nazário",
    image: "",
    nationality: "Brazil",
    nationalityFlag: "https://flagcdn.com/br.svg",
    position: "Forward",
    teams: [
      { teamId: "cruzeiro", teamName: "Cruzeiro", startYear: 1993, endYear: 1994 },
      { teamId: "psv", teamName: "PSV Eindhoven", startYear: 1994, endYear: 1996 },
      { teamId: "barcelona", teamName: "Barcelona", startYear: 1996, endYear: 1997 },
      { teamId: "inter", teamName: "Inter Milan", startYear: 1997, endYear: 2002 },
      { teamId: "real-madrid", teamName: "Real Madrid", startYear: 2002, endYear: 2007 },
      { teamId: "milan", teamName: "AC Milan", startYear: 2007, endYear: 2008 },
    ],
  },
  {
    id: "ronaldinho",
    name: "Ronaldinho",
    image: "",
    nationality: "Brazil",
    nationalityFlag: "https://flagcdn.com/br.svg",
    position: "Forward",
    teams: [
      { teamId: "gremio", teamName: "Grêmio", startYear: 1998, endYear: 2001 },
      { teamId: "psg", teamName: "Paris Saint-Germain", startYear: 2001, endYear: 2003 },
      { teamId: "barcelona", teamName: "Barcelona", startYear: 2003, endYear: 2008 },
      { teamId: "milan", teamName: "AC Milan", startYear: 2008, endYear: 2011 },
    ],
  },
  {
    id: "r9",
    name: "Ronaldo Nazário",
    image: "",
    nationality: "Brazil",
    nationalityFlag: "https://flagcdn.com/br.svg",
    position: "Forward",
    teams: [
      { teamId: "cruzeiro", teamName: "Cruzeiro", startYear: 1993, endYear: 1994 },
      { teamId: "psv", teamName: "PSV Eindhoven", startYear: 1994, endYear: 1996 },
      { teamId: "barcelona", teamName: "Barcelona", startYear: 1996, endYear: 1997 },
      { teamId: "inter", teamName: "Inter Milan", startYear: 1997, endYear: 2002 },
      { teamId: "real-madrid", teamName: "Real Madrid", startYear: 2002, endYear: 2007 },
      { teamId: "milan", teamName: "AC Milan", startYear: 2007, endYear: 2008 },
    ],
  },
  {
    id: "zidane",
    name: "Zinedine Zidane",
    image: "",
    nationality: "France",
    nationalityFlag: "https://flagcdn.com/fr.svg",
    position: "Midfielder",
    teams: [
      { teamId: "cannes", teamName: "AS Cannes", startYear: 1989, endYear: 1992 },
      { teamId: "bordeaux", teamName: "FC Girondins Bordeaux", startYear: 1992, endYear: 1996 },
      { teamId: "juventus", teamName: "Juventus", startYear: 1996, endYear: 2001 },
      { teamId: "real-madrid", teamName: "Real Madrid", startYear: 2001, endYear: 2006 },
    ],
  },
  {
    id: "henry",
    name: "Thierry Henry",
    image: "",
    nationality: "France",
    nationalityFlag: "https://flagcdn.com/fr.svg",
    position: "Forward",
    teams: [
      { teamId: "monaco", teamName: "AS Monaco", startYear: 1994, endYear: 1999 },
      { teamId: "juventus", teamName: "Juventus", startYear: 1999, endYear: 1999 },
      { teamId: "arsenal", teamName: "Arsenal", startYear: 1999, endYear: 2007 },
      { teamId: "barcelona", teamName: "Barcelona", startYear: 2007, endYear: 2010 },
      { teamId: "ny-red-bulls", teamName: "New York Red Bulls", startYear: 2010, endYear: 2014 },
    ],
  },
  {
    id: "beckham",
    name: "David Beckham",
    image: "",
    nationality: "England",
    nationalityFlag: "https://flagcdn.com/gb-eng.svg",
    position: "Midfielder",
    teams: [
      { teamId: "man-united", teamName: "Manchester United", startYear: 1992, endYear: 2003 },
      { teamId: "real-madrid", teamName: "Real Madrid", startYear: 2003, endYear: 2007 },
      { teamId: "la-galaxy", teamName: "LA Galaxy", startYear: 2007, endYear: 2012 },
      { teamId: "milan", teamName: "AC Milan", startYear: 2009, endYear: 2010 },
      { teamId: "psg", teamName: "Paris Saint-Germain", startYear: 2012, endYear: 2013 },
    ],
  },
  {
    id: "xavi",
    name: "Xavi Hernández",
    image: "",
    nationality: "Spain",
    nationalityFlag: "https://flagcdn.com/es.svg",
    position: "Midfielder",
    teams: [
      { teamId: "barcelona", teamName: "Barcelona", startYear: 1998, endYear: 2015 },
      { teamId: "al-sadd", teamName: "Al Sadd", startYear: 2015, endYear: 2019 },
    ],
  },
  {
    id: "iniesta",
    name: "Andrés Iniesta",
    image: "",
    nationality: "Spain",
    nationalityFlag: "https://flagcdn.com/es.svg",
    position: "Midfielder",
    teams: [
      { teamId: "barcelona", teamName: "Barcelona", startYear: 2002, endYear: 2018 },
      { teamId: "vissel-kobe", teamName: "Vissel Kobe", startYear: 2018, endYear: 2023 },
    ],
  },
  {
    id: "ronaldo",
    name: "Cristiano Ronaldo",
    image: "",
    nationality: "Portugal",
    nationalityFlag: "https://flagcdn.com/pt.svg",
    position: "Forward",
    teams: [
      { teamId: "sporting", teamName: "Sporting CP", startYear: 2002, endYear: 2003 },
      { teamId: "man-united", teamName: "Manchester United", startYear: 2003, endYear: 2009 },
      { teamId: "real-madrid", teamName: "Real Madrid", startYear: 2009, endYear: 2018 },
      { teamId: "juventus", teamName: "Juventus", startYear: 2018, endYear: 2021 },
      { teamId: "man-united", teamName: "Manchester United", startYear: 2021, endYear: 2022 },
      { teamId: "al-nassr", teamName: "Al Nassr", startYear: 2023, endYear: undefined },
    ],
  },
  {
    id: "rooney",
    name: "Wayne Rooney",
    image: "",
    nationality: "England",
    nationalityFlag: "https://flagcdn.com/gb-eng.svg",
    position: "Forward",
    teams: [
      { teamId: "everton", teamName: "Everton", startYear: 2002, endYear: 2004 },
      { teamId: "man-united", teamName: "Manchester United", startYear: 2004, endYear: 2017 },
      { teamId: "everton", teamName: "Everton", startYear: 2017, endYear: 2018 },
      { teamId: "dc-united", teamName: "D.C. United", startYear: 2018, endYear: 2020 },
    ],
  },
  {
    id: "griezmann",
    name: "Antoine Griezmann",
    image: "",
    nationality: "France",
    nationalityFlag: "https://flagcdn.com/fr.svg",
    position: "Forward",
    teams: [
      { teamId: "real-sociedad", teamName: "Real Sociedad", startYear: 2009, endYear: 2014 },
      { teamId: "atletico", teamName: "Atlético Madrid", startYear: 2014, endYear: 2019 },
      { teamId: "barcelona", teamName: "Barcelona", startYear: 2019, endYear: 2021 },
      { teamId: "atletico", teamName: "Atlético Madrid", startYear: 2021, endYear: undefined },
    ],
  },
  {
    id: "demba-ba",
    name: "Demba Ba",
    image: "",
    nationality: "Senegal",
    nationalityFlag: "https://flagcdn.com/sn.svg",
    position: "Forward",
    teams: [
      { teamId: "chelsea", teamName: "Chelsea", startYear: 2013, endYear: 2014 },
    ],
  },
  {
    id: "lampard",
    name: "Frank Lampard",
    image: "",
    nationality: "England",
    nationalityFlag: "https://flagcdn.com/gb-eng.svg",
    position: "Midfielder",
    teams: [
      { teamId: "west-ham", teamName: "West Ham United", startYear: 1995, endYear: 2001 },
      { teamId: "chelsea", teamName: "Chelsea", startYear: 2001, endYear: 2014 },
      { teamId: "man-city", teamName: "Manchester City", startYear: 2014, endYear: 2015 },
    ],
  },
  {
    id: "gerrard",
    name: "Steven Gerrard",
    image: "",
    nationality: "England",
    nationalityFlag: "https://flagcdn.com/gb-eng.svg",
    position: "Midfielder",
    teams: [
      { teamId: "liverpool", teamName: "Liverpool", startYear: 1998, endYear: 2015 },
      { teamId: "la-galaxy", teamName: "LA Galaxy", startYear: 2015, endYear: 2016 },
    ],
  },
  {
    id: "torres",
    name: "Fernando Torres",
    image: "",
    nationality: "Spain",
    nationalityFlag: "https://flagcdn.com/es.svg",
    position: "Forward",
    teams: [
      { teamId: "atletico", teamName: "Atlético Madrid", startYear: 2001, endYear: 2007 },
      { teamId: "liverpool", teamName: "Liverpool", startYear: 2007, endYear: 2011 },
      { teamId: "chelsea", teamName: "Chelsea", startYear: 2011, endYear: 2014 },
      { teamId: "milan", teamName: "AC Milan", startYear: 2014, endYear: 2015 },
      { teamId: "atletico", teamName: "Atlético Madrid", startYear: 2015, endYear: 2018 },
    ],
  },
  {
    id: "suarez",
    name: "Luis Suárez",
    image: "",
    nationality: "Uruguay",
    nationalityFlag: "https://flagcdn.com/uy.svg",
    position: "Forward",
    teams: [
      { teamId: "ajax", teamName: "Ajax", startYear: 2007, endYear: 2011 },
      { teamId: "liverpool", teamName: "Liverpool", startYear: 2011, endYear: 2014 },
      { teamId: "barcelona", teamName: "Barcelona", startYear: 2014, endYear: 2020 },
      { teamId: "atletico", teamName: "Atlético Madrid", startYear: 2020, endYear: 2022 },
      { teamId: "gremio", teamName: "Grêmio", startYear: 2023, endYear: 2023 },
      { teamId: "inter-miami", teamName: "Inter Miami", startYear: 2024, endYear: undefined },
    ],
  },
  {
    id: "aguero",
    name: "Sergio Agüero",
    image: "",
    nationality: "Argentina",
    nationalityFlag: "https://flagcdn.com/ar.svg",
    position: "Forward",
    teams: [
      { teamId: "independiente", teamName: "Independiente", startYear: 2005, endYear: 2006 },
      { teamId: "atletico", teamName: "Atlético Madrid", startYear: 2006, endYear: 2011 },
      { teamId: "man-city", teamName: "Manchester City", startYear: 2011, endYear: 2021 },
      { teamId: "barcelona", teamName: "Barcelona", startYear: 2021, endYear: 2021 },
    ],
  },
  {
    id: "drogba",
    name: "Didier Drogba",
    image: "",
    nationality: "Ivory Coast",
    nationalityFlag: "https://flagcdn.com/ci.svg",
    position: "Forward",
    teams: [
      { teamId: "marseille", teamName: "Olympique Marseille", startYear: 2003, endYear: 2004 },
      { teamId: "chelsea", teamName: "Chelsea", startYear: 2004, endYear: 2012 },
      { teamId: "galatasaray", teamName: "Galatasaray", startYear: 2013, endYear: 2014 },
      { teamId: "chelsea", teamName: "Chelsea", startYear: 2014, endYear: 2015 },
    ],
  },
  {
    id: "ibrahimovic",
    name: "Zlatan Ibrahimović",
    image: "",
    nationality: "Sweden",
    nationalityFlag: "https://flagcdn.com/se.svg",
    position: "Forward",
    teams: [
      { teamId: "ajax", teamName: "Ajax", startYear: 2001, endYear: 2004 },
      { teamId: "juventus", teamName: "Juventus", startYear: 2004, endYear: 2006 },
      { teamId: "inter", teamName: "Inter Milan", startYear: 2006, endYear: 2009 },
      { teamId: "barcelona", teamName: "Barcelona", startYear: 2009, endYear: 2011 },
      { teamId: "milan", teamName: "AC Milan", startYear: 2011, endYear: 2012 },
      { teamId: "psg", teamName: "Paris Saint-Germain", startYear: 2012, endYear: 2016 },
      { teamId: "man-united", teamName: "Manchester United", startYear: 2016, endYear: 2017 },
      { teamId: "la-galaxy", teamName: "LA Galaxy", startYear: 2018, endYear: 2019 },
      { teamId: "milan", teamName: "AC Milan", startYear: 2020, endYear: 2023 },
    ],
  },
  {
    id: "kaka",
    name: "Kaká",
    image: "",
    nationality: "Brazil",
    nationalityFlag: "https://flagcdn.com/br.svg",
    position: "Midfielder",
    teams: [
      { teamId: "sao-paulo", teamName: "São Paulo", startYear: 2001, endYear: 2003 },
      { teamId: "milan", teamName: "AC Milan", startYear: 2003, endYear: 2009 },
      { teamId: "real-madrid", teamName: "Real Madrid", startYear: 2009, endYear: 2013 },
      { teamId: "milan", teamName: "AC Milan", startYear: 2013, endYear: 2014 },
      { teamId: "orlando", teamName: "Orlando City", startYear: 2014, endYear: 2017 },
    ],
  },
  {
    id: "neuer",
    name: "Manuel Neuer",
    image: "",
    nationality: "Germany",
    nationalityFlag: "https://flagcdn.com/de.svg",
    position: "Goalkeeper",
    teams: [
      { teamId: "schalke", teamName: "Schalke 04", startYear: 2006, endYear: 2011 },
      { teamId: "bayern", teamName: "Bayern Munich", startYear: 2011, endYear: undefined },
    ],
  },
  {
    id: "muller",
    name: "Thomas Müller",
    image: "",
    nationality: "Germany",
    nationalityFlag: "https://flagcdn.com/de.svg",
    position: "Forward",
    teams: [
      { teamId: "bayern", teamName: "Bayern Munich", startYear: 2009, endYear: undefined },
    ],
  },
  {
    id: "ribery",
    name: "Franck Ribéry",
    image: "",
    nationality: "France",
    nationalityFlag: "https://flagcdn.com/fr.svg",
    position: "Forward",
    teams: [
      { teamId: "marseille", teamName: "Olympique Marseille", startYear: 2005, endYear: 2007 },
      { teamId: "bayern", teamName: "Bayern Munich", startYear: 2007, endYear: 2019 },
      { teamId: "fiorentina", teamName: "Fiorentina", startYear: 2019, endYear: 2021 },
    ],
  },
  {
    id: "ribery",
    name: "Franck Ribéry",
    image: "",
    nationality: "France",
    nationalityFlag: "https://flagcdn.com/fr.svg",
    position: "Forward",
    teams: [
      { teamId: "marseille", teamName: "Olympique Marseille", startYear: 2005, endYear: 2007 },
      { teamId: "bayern", teamName: "Bayern Munich", startYear: 2007, endYear: 2019 },
      { teamId: "fiorentina", teamName: "Fiorentina", startYear: 2019, endYear: 2021 },
    ],
  },
  {
    id: "robben",
    name: "Arjen Robben",
    image: "",
    nationality: "Netherlands",
    nationalityFlag: "https://flagcdn.com/nl.svg",
    position: "Forward",
    teams: [
      { teamId: "psv", teamName: "PSV Eindhoven", startYear: 2002, endYear: 2004 },
      { teamId: "chelsea", teamName: "Chelsea", startYear: 2004, endYear: 2007 },
      { teamId: "real-madrid", teamName: "Real Madrid", startYear: 2007, endYear: 2009 },
      { teamId: "bayern", teamName: "Bayern Munich", startYear: 2009, endYear: 2019 },
    ],
  },
  {
    id: "ramos",
    name: "Sergio Ramos",
    image: "",
    nationality: "Spain",
    nationalityFlag: "https://flagcdn.com/es.svg",
    position: "Defender",
    teams: [
      { teamId: "sevilla", teamName: "Sevilla", startYear: 2004, endYear: 2005 },
      { teamId: "real-madrid", teamName: "Real Madrid", startYear: 2005, endYear: 2021 },
      { teamId: "psg", teamName: "Paris Saint-Germain", startYear: 2021, endYear: 2023 },
      { teamId: "sevilla", teamName: "Sevilla", startYear: 2023, endYear: undefined },
    ],
  },
  {
    id: "alaba",
    name: "David Alaba",
    image: "",
    nationality: "Austria",
    nationalityFlag: "https://flagcdn.com/at.svg",
    position: "Defender",
    teams: [
      { teamId: "bayern", teamName: "Bayern Munich", startYear: 2010, endYear: 2021 },
      { teamId: "real-madrid", teamName: "Real Madrid", startYear: 2021, endYear: undefined },
    ],
  },
  {
    id: "kimmich",
    name: "Joshua Kimmich",
    image: "",
    nationality: "Germany",
    nationalityFlag: "https://flagcdn.com/de.svg",
    position: "Midfielder",
    teams: [
      { teamId: "bayern", teamName: "Bayern Munich", startYear: 2015, endYear: undefined },
    ],
  },
  {
    id: "davies",
    name: "Alphonso Davies",
    image: "",
    nationality: "Canada",
    nationalityFlag: "https://flagcdn.com/ca.svg",
    position: "Defender",
    teams: [
      { teamId: "vancouver", teamName: "Vancouver Whitecaps", startYear: 2016, endYear: 2018 },
      { teamId: "bayern", teamName: "Bayern Munich", startYear: 2019, endYear: undefined },
    ],
  },
  {
    id: "de-ligt",
    name: "Matthijs de Ligt",
    image: "",
    nationality: "Netherlands",
    nationalityFlag: "https://flagcdn.com/nl.svg",
    position: "Defender",
    teams: [
      { teamId: "ajax", teamName: "Ajax", startYear: 2016, endYear: 2019 },
      { teamId: "juventus", teamName: "Juventus", startYear: 2019, endYear: 2022 },
      { teamId: "bayern", teamName: "Bayern Munich", startYear: 2022, endYear: undefined },
    ],
  },
  {
    id: "mane",
    name: "Sadio Mané",
    image: "",
    nationality: "Senegal",
    nationalityFlag: "https://flagcdn.com/sn.svg",
    position: "Forward",
    teams: [
      { teamId: "salzburg", teamName: "Red Bull Salzburg", startYear: 2012, endYear: 2014 },
      { teamId: "southampton", teamName: "Southampton", startYear: 2014, endYear: 2016 },
      { teamId: "liverpool", teamName: "Liverpool", startYear: 2016, endYear: 2022 },
      { teamId: "bayern", teamName: "Bayern Munich", startYear: 2022, endYear: 2023 },
      { teamId: "al-nassr", teamName: "Al Nassr", startYear: 2023, endYear: undefined },
    ],
  },
  {
    id: "firmino",
    name: "Roberto Firmino",
    image: "",
    nationality: "Brazil",
    nationalityFlag: "https://flagcdn.com/br.svg",
    position: "Forward",
    teams: [
      { teamId: "tsg", teamName: "1899 Hoffenheim", startYear: 2011, endYear: 2015 },
      { teamId: "liverpool", teamName: "Liverpool", startYear: 2015, endYear: 2023 },
      { teamId: "al-ahli", teamName: "Al Ahli", startYear: 2023, endYear: undefined },
    ],
  },
  {
    id: "dias",
    name: "Rúben Dias",
    image: "",
    nationality: "Portugal",
    nationalityFlag: "https://flagcdn.com/pt.svg",
    position: "Defender",
    teams: [
      { teamId: "benfica", teamName: "SL Benfica", startYear: 2017, endYear: 2020 },
      { teamId: "man-city", teamName: "Manchester City", startYear: 2020, endYear: undefined },
    ],
  },
  {
    id: "bruno",
    name: "Bruno Fernandes",
    image: "",
    nationality: "Portugal",
    nationalityFlag: "https://flagcdn.com/pt.svg",
    position: "Midfielder",
    teams: [
      { teamId: "udinese", teamName: "Udinese", startYear: 2013, endYear: 2016 },
      { teamId: "sampdoria", teamName: "Sampdoria", startYear: 2016, endYear: 2017 },
      { teamId: "sporting", teamName: "Sporting CP", startYear: 2017, endYear: 2020 },
      { teamId: "man-united", teamName: "Manchester United", startYear: 2020, endYear: undefined },
    ],
  },
  {
    id: "cancelo",
    name: "João Cancelo",
    image: "",
    nationality: "Portugal",
    nationalityFlag: "https://flagcdn.com/pt.svg",
    position: "Defender",
    teams: [
      { teamId: "benfica", teamName: "SL Benfica", startYear: 2014, endYear: 2015 },
      { teamId: "valencia", teamName: "Valencia", startYear: 2015, endYear: 2018 },
      { teamId: "juventus", teamName: "Juventus", startYear: 2018, endYear: 2019 },
      { teamId: "man-city", teamName: "Manchester City", startYear: 2019, endYear: 2023 },
      { teamId: "bayern", teamName: "Bayern Munich", startYear: 2023, endYear: 2023 },
      { teamId: "barcelona", teamName: "Barcelona", startYear: 2023, endYear: undefined },
    ],
  },
  {
    id: "dani-alves",
    name: "Dani Alves",
    image: "",
    nationality: "Brazil",
    nationalityFlag: "https://flagcdn.com/br.svg",
    position: "Defender",
    teams: [
      { teamId: "sevilla", teamName: "Sevilla", startYear: 2003, endYear: 2008 },
      { teamId: "barcelona", teamName: "Barcelona", startYear: 2008, endYear: 2017 },
      { teamId: "juventus", teamName: "Juventus", startYear: 2017, endYear: 2018 },
      { teamId: "psg", teamName: "Paris Saint-Germain", startYear: 2018, endYear: 2019 },
      { teamId: "sao-paulo", teamName: "São Paulo", startYear: 2019, endYear: 2021 },
      { teamId: "barcelona", teamName: "Barcelona", startYear: 2022, endYear: 2023 },
    ],
  },
  {
    id: "rashford",
    name: "Marcus Rashford",
    image: "",
    nationality: "England",
    nationalityFlag: "https://flagcdn.com/gb-eng.svg",
    position: "Forward",
    teams: [
      { teamId: "man-united", teamName: "Manchester United", startYear: 2016, endYear: undefined },
    ],
  },
  {
    id: "fernandinho",
    name: "Fernandinho",
    image: "",
    nationality: "Brazil",
    nationalityFlag: "https://flagcdn.com/br.svg",
    position: "Midfielder",
    teams: [
      { teamId: "shakhtar", teamName: "Shakhtar Donetsk", startYear: 2007, endYear: 2013 },
      { teamId: "man-city", teamName: "Manchester City", startYear: 2013, endYear: 2022 },
    ],
  },
  {
    id: "silva",
    name: "Bernardo Silva",
    image: "",
    nationality: "Portugal",
    nationalityFlag: "https://flagcdn.com/pt.svg",
    position: "Midfielder",
    teams: [
      { teamId: "benfica", teamName: "SL Benfica", startYear: 2014, endYear: 2015 },
      { teamId: "monaco", teamName: "AS Monaco", startYear: 2015, endYear: 2017 },
      { teamId: "man-city", teamName: "Manchester City", startYear: 2017, endYear: undefined },
    ],
  },
  {
    id: "sterling",
    name: "Raheem Sterling",
    image: "",
    nationality: "England",
    nationalityFlag: "https://flagcdn.com/gb-eng.svg",
    position: "Forward",
    teams: [
      { teamId: "liverpool", teamName: "Liverpool", startYear: 2012, endYear: 2015 },
      { teamId: "man-city", teamName: "Manchester City", startYear: 2015, endYear: 2022 },
      { teamId: "chelsea", teamName: "Chelsea", startYear: 2022, endYear: undefined },
    ],
  },
  {
    id: "vardy",
    name: "Jamie Vardy",
    image: "",
    nationality: "England",
    nationalityFlag: "https://flagcdn.com/gb-eng.svg",
    position: "Forward",
    teams: [
      { teamId: "leicester", teamName: "Leicester City", startYear: 2012, endYear: undefined },
    ],
  },
  {
    id: "maguire",
    name: "Harry Maguire",
    image: "",
    nationality: "England",
    nationalityFlag: "https://flagcdn.com/gb-eng.svg",
    position: "Defender",
    teams: [
      { teamId: "hull", teamName: "Hull City", startYear: 2014, endYear: 2017 },
      { teamId: "leicester", teamName: "Leicester City", startYear: 2017, endYear: 2019 },
      { teamId: "man-united", teamName: "Manchester United", startYear: 2019, endYear: undefined },
    ],
  },
  {
    id: "lewandowski",
    name: "Robert Lewandowski",
    image: "",
    nationality: "Poland",
    nationalityFlag: "https://flagcdn.com/pl.svg",
    position: "Forward",
    teams: [
      { teamId: "lech", teamName: "Lech Poznań", startYear: 2008, endYear: 2010 },
      { teamId: "dortmund", teamName: "Borussia Dortmund", startYear: 2010, endYear: 2014 },
      { teamId: "bayern", teamName: "Bayern Munich", startYear: 2014, endYear: 2022 },
      { teamId: "barcelona", teamName: "Barcelona", startYear: 2022, endYear: undefined },
    ],
  },
  {
    id: "hazard",
    name: "Eden Hazard",
    image: "",
    nationality: "Belgium",
    nationalityFlag: "https://flagcdn.com/be.svg",
    position: "Forward",
    teams: [
      { teamId: "lille", teamName: "Lille OSC", startYear: 2007, endYear: 2012 },
      { teamId: "chelsea", teamName: "Chelsea", startYear: 2012, endYear: 2019 },
      { teamId: "real-madrid", teamName: "Real Madrid", startYear: 2019, endYear: 2023 },
    ],
  },
  {
    id: "ozil",
    name: "Mesut Özil",
    image: "",
    nationality: "Germany",
    nationalityFlag: "https://flagcdn.com/de.svg",
    position: "Midfielder",
    teams: [
      { teamId: "schalke", teamName: "Schalke 04", startYear: 2006, endYear: 2008 },
      { teamId: "werder", teamName: "Werder Bremen", startYear: 2008, endYear: 2010 },
      { teamId: "real-madrid", teamName: "Real Madrid", startYear: 2010, endYear: 2013 },
      { teamId: "arsenal", teamName: "Arsenal", startYear: 2013, endYear: 2021 },
    ],
  },
  {
    id: "pogba",
    name: "Paul Pogba",
    image: "",
    nationality: "France",
    nationalityFlag: "https://flagcdn.com/fr.svg",
    position: "Midfielder",
    teams: [
      { teamId: "man-united", teamName: "Manchester United", startYear: 2011, endYear: 2012 },
      { teamId: "juventus", teamName: "Juventus", startYear: 2012, endYear: 2016 },
      { teamId: "man-united", teamName: "Manchester United", startYear: 2016, endYear: 2022 },
      { teamId: "juventus", teamName: "Juventus", startYear: 2022, endYear: 2024 },
    ],
  },
  {
    id: "vini",
    name: "Vinícius Jr",
    image: "",
    nationality: "Brazil",
    nationalityFlag: "https://flagcdn.com/br.svg",
    position: "Forward",
    teams: [
      { teamId: "flamengo", teamName: "Flamengo", startYear: 2017, endYear: 2018 },
      { teamId: "real-madrid", teamName: "Real Madrid", startYear: 2018, endYear: undefined },
    ],
  },
  {
    id: "mendy",
    name: "Ferland Mendy",
    image: "",
    nationality: "France",
    nationalityFlag: "https://flagcdn.com/fr.svg",
    position: "Defender",
    teams: [
      { teamId: "lyon", teamName: "Olympique Lyon", startYear: 2015, endYear: 2019 },
      { teamId: "real-madrid", teamName: "Real Madrid", startYear: 2019, endYear: undefined },
    ],
  },
  {
    id: "militao",
    name: "Éder Militão",
    image: "",
    nationality: "Brazil",
    nationalityFlag: "https://flagcdn.com/br.svg",
    position: "Defender",
    teams: [
      { teamId: "sao-paulo", teamName: "São Paulo", startYear: 2017, endYear: 2019 },
      { teamId: "porto", teamName: "FC Porto", startYear: 2019, endYear: 2019 },
      { teamId: "real-madrid", teamName: "Real Madrid", startYear: 2019, endYear: undefined },
    ],
  },
  {
    id: "tchouameni",
    name: "Aurélien Tchouaméni",
    image: "",
    nationality: "France",
    nationalityFlag: "https://flagcdn.com/fr.svg",
    position: "Midfielder",
    teams: [
      { teamId: "bordeaux", teamName: "FC Girondins Bordeaux", startYear: 2018, endYear: 2020 },
      { teamId: "monaco", teamName: "AS Monaco", startYear: 2020, endYear: 2022 },
      { teamId: "real-madrid", teamName: "Real Madrid", startYear: 2022, endYear: undefined },
    ],
  },
  {
    id: "camavinga",
    name: "Eduardo Camavinga",
    image: "",
    nationality: "France",
    nationalityFlag: "https://flagcdn.com/fr.svg",
    position: "Midfielder",
    teams: [
      { teamId: "rennes", teamName: "Stade Rennais", startYear: 2018, endYear: 2021 },
      { teamId: "real-madrid", teamName: "Real Madrid", startYear: 2021, endYear: undefined },
    ],
  },
]

export function getUniquePlayers(): Player[] {
  const seen = new Set<string>()
  return SEEDED_PLAYERS.filter((p) => {
    if (seen.has(p.id)) return false
    seen.add(p.id)
    return true
  })
}
